---
title: "HAI AR species abundance in the environment"
output:
  html_document:
    df_print: paged
---

### HAI abundance in the environment

Load generic libraries
```{r}
source('configuration.r')
```

Load plot specific libraries
```{r}
library(ggbeeswarm)
```

Read and process nanopore data
```{r}
meta.nanopore <- read.table('../metadata/nanopore.metadata.txt',head=T,sep='\t')
df.nanopore <- read.table('../tables/genome_info.dat', sep='\t', head=T) %>% 
  merge(meta.nanopore, by='Nanopore_ID') %>%
  unite('lab', Species_name, Illumina_Library_ID, sep='#', remove=FALSE)
df.nanopore
```

Read and process illumina data
```{r}
meta.illumina <- read.table('../metadata/illumina_metadata.txt', head=TRUE, row.names=2)
df.metaphlan <- 
  read.table('../output_tables/metagenomics.metaphlan2.table.filtered.s', head=TRUE, stringsAsFactors=FALSE) %>% 
    rownames_to_column('Index') %>% 
    mutate(Index=str_replace(Index, 's__', '')) %>%
    melt %>% 
    unite('lab', Index, variable, sep='#', remove=FALSE) 
df.metaphlan
```

Merge data
```{r}
dat <-
  merge(df.metaphlan, df.nanopore, by='lab') %>% 
  mutate(lab=paste0(Species_name,'@',Nanopore_ID, '@', Illumina_Library_ID)) %>% 
  mutate(species=str_replace(Species_name, '_', ' '))
dat
```

Select HAI species of interest
```{r}
dat <-  filter(dat, grepl("Burkholderia", species) | 
               species %in% c("Acinetobacter baumannii","Candida albicans",
                         "Clostridium difficile", "Clostridium sordellii", 
                         "Klebsiella pneumoniae", "Klebsiella oxytoca",
                         "Escherichia coli", "Staphylococcus aureus",
                         "Pseudomonas aeruginosa","Mycobacterium abscessus",
                         "Mycobacterium tuberculosis","Enterococcus faecalis",
                         "Enterococcus faecium", "Staphylococcus epidermidis"))
```

Plot
```{r}
plot.dat <- group_by(dat,Species_name) %>% 
  tally() %>%
  merge(dat, by='Species_name') %>%
  filter(n>19)

o <- c('Ill','BHI', 'AMP', 'CHLOR', 'KAN', 'STREP', 'TET')

# mean((
# distinct(plot.dat, Index, variable, value) %>% 
#   group_by(Index) %>% 
#   summarise(median=median(value))
# )$median) ## summary statistics

g <- ggplot(data=plot.dat, aes(x=factor(Antibiotics,level=o), y=log(value+1,2),color=Antibiotics)) +
  geom_quasirandom(dodge.width = 1, alpha=0.8, size=0.3) +
  scale_color_npg(guide=FALSE) + 
  labs(x='Antibiotics', y='log2(% + 1)')+
  theme(axis.text.x = element_text(angle=40, hjust=1, size=8),
        strip.text = element_text(size=7, face='bold.italic'))
g + facet_wrap(~species,nrow=3)
```

Save plot
```{r, echo=FALSE}
ggsave('../plots/fig3c.hai_ar_species_abundance_in_illumina.svg', g + facet_wrap(~species,nrow=1), 
       width=12, height=3)
```

### Session informaton
```{r}
sessionInfo()
```