---
title: "Genome comparison of isolates from hospital and patient"
output:
  html_document:
    df_print: paged
---

### Genome comparison of isolates from hospital and patient

Load generic libraries
```{r message=FALSE}
source('configuration.r')
```

Load plot specific libraries
```{r message=FALSE}
library(foreach)
library(ggtree)
library(ape)
```

Function to plot tree
```{r}
get_tree_data <- function(species, filter.patient.only=TRUE, outlier='', get.dist=FALSE){
  dist.dat <- read.table(paste0('../tables/',species,'_mummer_heatmap.dat'))
  meta <- read.table('../output_tables/merged_assembly_metadata.tsv', head=TRUE, sep='\t') %>% filter(Species==species)
  idx <- rownames(dist.dat) %in% (filter(meta, Genome_quality=='HIGH_QUAL'))$Genome_ID |## High quality genomes
    str_detect(rownames(dist.dat), 'G_')
  dist.dat <- dist.dat[idx, idx]
  if(get.dist) return(dist.dat)
  clustering.all <- hclust(as.dist(dist.dat), method='single')
  clusters.all <- cutree(clustering.all, h=0.001)
  strains <- foreach(x=unique(clusters.all), .combine=rbind) %do% {
    tmp <- clusters.all[clusters.all==x]
    dat <- data.frame(strain=tmp[order(names(tmp), decreasing = T)][1]) ## select hospital if possible
    dat$n <- length(tmp)
    dat$Hospital <- sum(str_detect(names(tmp), 's'))/dat$n
    dat$Patient <- sum(str_detect(names(tmp), 'G'))/dat$n
    dat$rep <- row.names(dat)
    dat[,c(5,1,2,3,4)]
  }
  
  ## filter patient only strains
  if(filter.patient.only) strains <- filter(strains, Patient<1)
  ## filter strains that are very different
  strains <- filter(strains, rep!=outlier) 
  strains$lab <- ifelse(strains$Hospital==1, 'Hospital', 'Hospital/Patient')
  idx <- strains$rep
  
  clustering <- hclust(as.dist(dist.dat[idx, idx]), method='average')
  
  merge(data.frame(clusters=clusters.all), meta, by.x=0, by.y=1, all.x=TRUE) %>%
     mutate(strain=paste0('s', clusters)) %>%
     mutate(lab=ifelse(str_detect(Row.names, 's'), 'Hospital', 'Patient')) -> merged
  
  mutate_at(merged, vars(Antibiotics), function(x) ifelse(merged$lab=='Patient', 'MET', as.character(x)) ) %>%
    select(clusters, Antibiotics) %>% group_by(clusters, Antibiotics) %>% 
    count() %>% mutate(n=Antibiotics) %>% 
    spread(Antibiotics,n,fill=NA) %>%
    merge(x=strains, y=., by.x=2, by.y=1) %>% 
    select(-n, -strain, -BHI) %>% data.frame(row.names = 'rep') -> antibiotics
  
  select(antibiotics, AMP, CHLOR, KAN, STREP, TET) -> anno
  # anno <- antibiotics %>% 
  #   mutate_at(vars(AMP, CHLOR, KAN, STREP, TET), function(x) ifelse(x!='0', x, NA))
  rownames(anno) <- rownames(antibiotics)
  
  # ## generate barplot
  # bars <- foreach(r=1:nrow(strains)) %do% {
  #   data <- melt(strains[r,], id.vars = c('n', 'strain', 'rep')) 
  #   ggplot(data, aes(x=1, y=value, fill= variable, width=n)) +
  #     geom_bar(stat='identity', alpha=1) +
  #     coord_flip() +
  #     scale_fill_npg() +
  #     theme_inset()
  # }
  # names(bars) <- 1:length(bars)
  list(anno=anno, strains=strains, clustering=clustering)
}

test_enrichment <- function(dat){
  anti <- apply(dat$anno, 1, function(x) sum(!is.na(x))) > 2 ## resistant to > 2
  patient <- dat$strains$lab=="Hospital/Patient"             ## shared strain
  c1 <- sum(anti & patient)
  c2 <- sum(!anti & patient)
  c3 <- sum(anti & !patient)
  c4 <- sum(!anti & !patient)
  fisher.test(matrix(c(c1,c2,c3,c4), 2,2))$p.value
}
```


#### *Staphylococcus aureus*

```{r fig.height=6, fig.width=6, message=FALSE}
colors <- pal_npg('nrc')(9)

dat <- get_tree_data('Staphylococcus_aureus', outlier = '')
attach(dat)
## create a tree
p <- ggtree(as.phylo(clustering), color=colors[3], lwd=1) %<+%
  strains +
  geom_tippoint(aes(size=n, color=lab)) +
  geom_tiplab(aes(label=paste0('s', strain)), color=colors[3],size=4, hjust=1, fontface='bold', offset=1.3e-3) +
  scale_size_continuous(trans='log2') + 
  scale_shape_manual(values=c(21,19)) + 
  scale_color_manual(values=c('grey','black')) + 
  geom_treescale(x=0, y=15, width=0.001, color = colors[3], linesize=2) 
## Add heatmap
dd <- rownames_to_column(anno) %>% melt(id.vars='rowname')
p1 <- facet_plot(p , "Antibiotics resistance profile", 
                 data=dd,
                 geom_tile, aes(x = as.numeric(variable),  fill = value), color='white', lwd=2) +
  scale_fill_manual(values=colors[c(1,5,2,6,4)],na.value='white') + theme(legend.position = 'right')
tree1 <- facet_widths(p1, c(2,1))

test_enrichment(dat)
# ## Add bar plot
# tree <- inset(tree, bars, width=0.0006, height=1.4, hjust=-0.0003)
# ## Add legend for bars
# l1 <- cowplot::get_legend(bars[[1]] + theme_bw() + theme(legend.title =element_blank()))
# l2 <- cowplot::get_legend(tree)
# l <- cowplot::plot_grid(l1, l2, nrow=2)
# tree <- cowplot::plot_grid(l, tree + theme(legend.position="none"),
#           rel_widths=c(0.1,1) , nrow=1)
tree1
```

#### *Elizabethkingia anophelis*

```{r fig.height=2.5, fig.width=6, message=FALSE}
dat <- get_tree_data('Elizabethkingia_anophelis',  outlier = '')
attach(dat)
## create a tree
p <- ggtree(as.phylo(clustering), color=colors[1], lwd=1) %<+%
  strains +
  geom_tippoint(aes(size=n, color=lab)) +
  geom_tiplab(aes(label=paste0('s', strain)), color=colors[1],size=4, hjust=1, fontface='bold', offset=5e-3) +
  scale_size_continuous(trans='log2', limits=c(1,64)) + 
  scale_shape_manual(values=c(21,19)) + 
  scale_color_manual(values=c('grey','black')) + 
  geom_treescale(x=0.002, y=5, width=0.001,color = colors[1], linesize=2) 
## Add heatmap
dd <- rownames_to_column(anno) %>% melt(id.vars='rowname')
p1 <- facet_plot(p , "Antibiotics resistance profile", 
                 data=dd,
                 geom_tile, aes(x = as.numeric(variable),  fill = value), color='white', lwd=2) +
  scale_fill_manual(values=colors[c(1,5,2,6,4)],na.value='white') + theme(legend.position = 'right')

tree2 <- facet_widths(p1, c(2,1))
test_enrichment(dat)

tree2
```

#### *Acinetobacter baumannii*

```{r fig.height=9, fig.width=8, message=FALSE}
dat <- get_tree_data('Acinetobacter_baumannii',  outlier = '')
attach(dat)
## create a tree
p <- ggtree(as.phylo(clustering), color=colors[4], lwd=1) %<+%
  strains +
  geom_tippoint(aes(size=n, color=lab)) +
  geom_tiplab(aes(label=paste0('s', strain)), color=colors[4],size=4, hjust=1, fontface='bold', offset=1.3e-3) +
  scale_size_continuous(trans='log2', limits=c(1,64)) + 
  scale_shape_manual(values=c(21,19)) + 
  scale_color_manual(values=c('grey','black')) + 
  geom_treescale(x=0, y=20, width=0.001, color = colors[4], linesize=2) 
## Add heatmap
dd <- rownames_to_column(anno) %>% melt(id.vars='rowname')
p1 <- facet_plot(p , "Antibiotics resistance profile", 
                 data=dd,
                 geom_tile, aes(x = as.numeric(variable),  fill = value), color='white', lwd=2) +
  scale_fill_manual(values=colors[c(1,5,2,6,4)],na.value='white') + theme(legend.position = 'right')

tree3 <- facet_widths(p1, c(2,1))
test_enrichment(dat)

tree3
```

### *Staphylococcus epidermidis*

```{r fig.height=10, fig.width=7, message=FALSE}
dat <- get_tree_data('Staphylococcus_epidermidis', outlier = '')
attach(dat)
## create a tree
p <- ggtree(as.phylo(clustering), color=colors[2], lwd=1) %<+%
  strains +
  geom_tippoint(aes(size=n, color=lab)) +
  geom_tiplab(aes(label=paste0('s', strain)), color=colors[2],size=4, hjust=1, fontface='bold', offset=1.6e-3) +
  scale_size_continuous(trans='log2') + 
  scale_shape_manual(values=c(21,19)) + 
  scale_color_manual(values=c('grey','black')) + 
  geom_treescale(x=0, y=30, width=0.001, color = colors[2], linesize=2) 
## Add heatmap
dd <- rownames_to_column(anno) %>% melt(id.vars='rowname')
p1 <- facet_plot(p , "Antibiotics resistance profile", 
                 data=dd,
                 geom_tile, aes(x = as.numeric(variable),  fill = value), color='white', lwd=2) +
  scale_fill_manual(values=colors[c(1,5,2,6,4)],na.value='white') + theme(legend.position = 'right')

tree4 <- facet_widths(p1, c(2,1))
test_enrichment(dat)

tree4
```
### Put four trees at the same scale
```{r fig.height=10, fig.width=14}
p1 <- cowplot::plot_grid(tree1, tree3, ncol=1, rel_heights = c(0.75,1))
p2 <- cowplot::plot_grid(tree4, tree2, ncol=1, rel_heights = c(1,0.2))
cowplot::plot_grid(p1, p2, nrow=1)
```


### Overview tree
```{r fig.height=15, fig.width=10}
full_mat <- read.table('../tables/genome_mash_dist.dat')/4
idx <- 
  str_detect(row.names(full_mat), 'Staphylococcus_aureus') |
  str_detect(row.names(full_mat), 'Acinetobacter_baumannii') | 
  str_detect(row.names(full_mat), 'Staphylococcus_epidermidis') |
  str_detect(row.names(full_mat), 'Elizabethkingia_anophelis') 
full_mat <- full_mat[idx, idx]

meta <- read.table('../output_tables/merged_assembly_metadata.tsv', head=TRUE, sep='\t') %>% 
  select(Genome_ID, Species, Nanopore_ID) %>% unite(id, Species, Nanopore_ID, remove = FALSE)
## remove duplicates
idx <- rownames(full_mat) %in% meta$id
full_mat <- full_mat[idx, idx]
rownames(full_mat) <- colnames(full_mat) <- meta$Genome_ID[match(rownames(full_mat), meta$id)]

aux <- function(species){ ## function with side effect to fill in the mummer distance
  dist.ab <- get_tree_data(species, get.dist = TRUE)
  sel <- str_subset(rownames(dist.ab) ,'s_')
  full_mat[sel, sel] <<- dist.ab[sel, sel]
  return(sel)
}
## fill mash matrix with mummer distance
se <- aux('Staphylococcus_epidermidis')
sa <- aux('Staphylococcus_aureus')
ab <- aux('Acinetobacter_baumannii')
ea <- aux('Elizabethkingia_anophelis')

clustering <- hclust(as.dist(full_mat), method='single')
#anno <- meta[match(rownames(full_mat), meta$genomeID), ]
tree <- groupOTU(as.phylo(clustering), list(ea=ea, se=se, sa=sa, ab=ab))

p <- ggtree(tree, aes(color=group) , lwd=1.5) + 
  ##geom_text2(aes(subset=!isTip, label=node), hjust=-0.8) + 
  scale_color_manual(values=c("black", colors[c(4,1,3,2)])) +
  geom_treescale(x=0, y=550, width=0.01, linesize=3, offset=3, fontsize = 10) + 
  geom_hilight(node=540, alpha=0.2, fill = colors[2]) +
  geom_hilight(node=535, alpha=0.2, fill = colors[4]) +
  geom_hilight(node=533, alpha=0.2, fill = colors[1]) +
  geom_hilight(node=539, alpha=0.2, fill = colors[3]) +
  theme(legend.position = 'left')
  ##flip(p, 533, 534) %>% flip(535,536) %>% flip(539, 540)
p
```


### Session informaton
```{r}
sessionInfo()
```