---
title: "Hive plot for phage distribution"
output:
  html_document:
    df_print: paged
---

### Clustering based on identity

Load generic libraries
```{r}
source('configuration.r')
```

Load plot specific libraries
```{r message=FALSE, warning=FALSE}
library(ape)
library(HiveR)
library(forcats)
```

Merge data
```{r}
mat <- read.table('../tables/phage_mummer_heatmap.dat', head=TRUE, stringsAsFactors = FALSE, comment.char = '!', sep='\t', row.names = 1)

df <- data.frame(Genome_ID=rownames(mat)) %>% 
  mutate(Nanopore_ID=str_extract(Genome_ID, "N[0-9]+_[A-Za-z]+[0-9]+")) 

meta.illumina <- read.table('../metadata/illumina_metadata.txt', head=TRUE)[,-2]
meta.nanopore <- read.table('../metadata/nanopore.metadata.txt', head=TRUE, sep='\t', strip.white = TRUE)
meta.merged <- merge(meta.nanopore, meta.illumina,
                     by.x='Illumina_Library_ID',
                     by.y='Library')
meta.merged <- merge(df, meta.merged,
                     by='Nanopore_ID') %>%
  select(Genome_ID, everything()) %>% 
  mutate(Species='Phage', Sample_type=fct_drop(Sample_type)) 

## fix names in metadata to be consistent with the manuscript
levels(meta.merged$Sample_type) <- str_replace_all(levels(meta.merged$Sample_type), c('handle-interior'='Handle'))
levels(meta.merged$Room_type) <- str_replace_all(levels(meta.merged$Room_type), c('cubicles'='wards', 'Non-cohort'='Standard'))
levels(meta.merged$Cubicle_room) <- str_replace_all(levels(meta.merged$Cubicle_room), c('Cubicle'='Ward'))
```


Cluster the phages based on mummer distance
```{r}
dist.dat <- mat
## collapsing into strains
cluster.full <- hclust(as.dist(dist.dat), method='single')
clusters <- cutree(cluster.full, h=0.001)

strains <- sapply(unique(clusters), function(x) clusters[clusters==x][1]) ## using first entry as the representative

dat <- merge(data.frame(clusters), meta.merged, by.x=0, by.y=1)
phage.meta <- read.table('../tables/phage_info.dat', stringsAsFactors = F, head=T, sep='\t')

dat <- merge(dat, phage.meta, by=1, all.x=TRUE) %>% 
  mutate(is_Circular=is_Circular=="True", is_Novel=is_Novel=="True")

# sel <- filter(dat, is_Novel) %>%
#   pull(clusters) %>% unique ## keep only circular ones

# ## filter cluster (keep clusters with size > X)
# sel <- table(dat$clusters) %>% data.frame() %>% 
#   arrange(desc(Freq)) %>% filter(Freq>0) %>% 
#   pull(Var1) %>% as.numeric()

dat.sel <- dat %>% 
  #filter(clusters %in% sel) %>% 
  mutate(clusters=as.numeric(as.factor(clusters))) ## relevel the clusters
write.table(dat.sel, '../output_tables/phage_selected_cluster_summary.tsv', row.names = F, col.names = T, sep='\t', quote=F)
```

### Novel phage analysis

```{r}
novel_clusters <- select(dat.sel, clusters, tmp=is_Novel) %>% 
  group_by(clusters) %>% 
  summarise(isNovel=any(tmp)) #, len=length(tmp), novel=sum(tmp)) ## sanity check
```

### Hive plot for species distribution

Generate edge data
```{r}
dat.sel %>% 
  distinct(Species, clusters, Sample_type, Room_type, ## Sample_ID.y, ## This is the same as using bed number to collapse
           timept, Cubicle_room) %>%  ## collapse antibiotics and beds
  mutate(clusters=sprintf("%02d", clusters)) %>%   
  mutate(label1='Strain', label2='Site', label3='Room') %>% 
  unite(n1,c(label1, Species, clusters), sep='=', remove=F) %>% 
  unite(n2,c(label2, Sample_type), sep='=', remove=F) %>% 
  unite(n3,c(label3, Room_type, Cubicle_room), sep='=',remove=F) %>% 
  select(-label1, -label2, -label3) -> edge_data

## select the phage with the most genomes
edge_data <- filter(edge_data, n1%in% 
         (edge_data %>% group_by(n1) %>% count %>% arrange(desc(n)))[1,]$n1)
```


Hive plot for phages
```{r fig.height=12, fig.width=12}
edge_plot <- edge_data
## strain_col <- 'orange'

rbind(data.frame(x1=edge_plot$n1, x2=edge_plot$n2, color=edge_plot$timept, stringsAsFactors = F) ,
           data.frame(x1=edge_plot$n1, x2=edge_plot$n3, color=edge_plot$timept, stringsAsFactors = F)
           ) %>% 
  group_by(x1, x2, color) %>% count() %>% 
  select(x1, x2, weight=n, color) %>% 
  arrange(desc(x1,x2)) -> e

hive <- edge2HPD(data.frame(e[,1:3]))
hive$nodes$axis <- as.integer(as.factor(str_split_fixed(hive$nodes$lab, '=', 2)[,1]))
hive$nodes$tag <- str_split_fixed(hive$nodes$lab, '=', 3)[,1] 
hive$nodes[hive$nodes$axis==1, ] <- arrange(hive$nodes[hive$nodes$axis==1, ], lab) ## sort the names on the room axis
## species color
novel_clusters <- novel_clusters[match(as.numeric((hive$nodes$lab[ hive$nodes$tag == 'Strain'] %>% 
                                                     str_split_fixed('=', 3))[,3]), novel_clusters$clusters),] ## reorder
hive$nodes$color[ hive$nodes$tag == 'Strain'] <- ifelse(novel_clusters$isNovel, "black", 'grey')
## site color
colors <- sapply(c(pal_simpsons('springfield')(16)), adjustcolor, alpha.f=0.9)
colormap <- data.frame(site=levels((edge_data$Sample_type)), col=pal_npg('nrc')(10)[c(5,7,2,3,10,4,1)], row.names = 1, stringsAsFactors = F)
site.id <- hive$nodes$tag=='Site'
hive$nodes$color[site.id] <- colormap[str_split_fixed(hive$nodes$lab, '=', 2)[site.id, 2], ]
## room color
colormap <-data.frame(room=unique(edge_data$Room_type), col=colors[c(13,15,16)], row.names = 1, stringsAsFactors = F)
room.id <- hive$nodes$tag=='Room'
hive$nodes$color[room.id] <- colormap[str_split_fixed(hive$nodes$lab[room.id], '=', 3)[,2], ]

hive$nodes$size=2
##hive$nodes$size[ hive$nodes$tag == 'Strain'] <- 1.5

hive$edges$weight <- hive$edges$weight*3-1
hive$edges$color <- ifelse(e$color<2, '#ff990055','#66ccff55')
#hive$edges$color <- ifelse(e$color<2,'#66ccff77',  '#ff330077')
tmp <- data.frame(node.lab=hive$nodes$lab, node.text=hive$nodes$lab, angle=0, radius=0, offset=0, hjust=1, vjust=0.5)
mutate(tmp, node.text=str_replace(node.text, 'Strain=.*=', 'Strain=s')) %>% 
  separate(col=node.text, into=c('lab','node.text'), '=', extra='merge') %>% 
  mutate(node.text=str_replace_all(node.text, '_', ' ')) %>% 
  mutate(node.text=str_replace_all(node.text, '=', ': ')) %>%
  #mutate(node.text=str_replace(node.text, 's[0-9]+', '')) %>% 
  mutate(offset=ifelse(lab=='Room' | lab=='Site' , -0.05, -0.03)) %>% 
  select(-lab) %>% View()
write.table('tmp_hive.txt', sep=',', quote=T, row.names = F, col.names = T)

plotHive(hive, ch=0.2, method='rank', bkgnd='white', anNodes = 'tmp_hive.txt',
        anNode.gpar=gpar(cex=1.5))
```





<!-- ### Save plots -->
<!-- ```{r message=FALSE, warning=FALSE} -->
<!-- pdf('../plots/xxxxx', width = 12, height = 12) -->
<!-- plotHive(hive, ch=0.2, method='ranknorm', bkgnd='white', anNodes = 'tmp_hive.txt', -->
<!--         anNode.gpar=gpar(cex=1.5)) -->
<!-- dev.off() -->
<!-- ``` -->

### Session informaton
```{r}
sessionInfo()
```

