---
title: "HAI AR assembly N50"
output:
  html_document:
    df_print: paged
---

### HAI AR assembly N50

Load generic libraries
```{r message=FALSE, warning=FALSE}
source('configuration.r')
```

Load plot specific libraries
```{r}
library(ggridges)
```

Read in and process data
```{r}
dat <- read.table('../tables/genome_info.dat', head=TRUE, sep='\t') %>% 
  mutate(species=str_replace(Species_name, '_',' '))
```

Select HAI species
```{r}
dat <-  filter(dat, grepl("Burkholderia", species) | 
               species %in% c("Acinetobacter baumannii","Candida albicans",
                         "Clostridium difficile", "Clostridium sordellii", 
                         "Klebsiella pneumoniae", "Klebsiella oxytoca",
                         "Escherichia coli", "Staphylococcus aureus",
                         "Pseudomonas aeruginosa","Mycobacterium abscessus",
                         "Mycobacterium tuberculosis","Enterococcus faecalis",
                         "Enterococcus faecium", "Staphylococcus epidermidis"))
```

Plot
```{r fig.height=6, fig.width=8}
plot.dat <- group_by(dat, species) %>% 
  tally() %>% 
  merge(dat, by='species') %>%
  mutate(species = str_replace(species, '[a-z]+ ', '. ')) %>% 
  filter(n>19) 
  

g <- ggplot(data =plot.dat, aes(y=species,x=N50/1e6, fill=species, height = ..density..)) + 
  geom_density_ridges(stat = "binline", bins = 15, scale = 0.8, draw_baseline = FALSE) +
  scale_fill_npg(guide=FALSE)+
  theme(axis.text.y = element_text(face='bold.italic',margin=margin(0,10,0,0)))  + 
  scale_x_log10() + 
  labs(y=NULL, x='N50 (MB)') +
  coord_cartesian(ylim =c(1,7.5))
g
```

Save plot
```{r, echo=FALSE}
ggsave('../plots/fig3b.hai_ar_species_nanopore_n50.svg', g,
       width=7, height=6)
```

### Session informaton
```{r}
sessionInfo()
```
