---
title: "Figure 2C - HAI AR assembly N50"
output:
  html_document:
    df_print: paged
---

### HAI AR assembly N50

Load generic libraries
```{r}
source('configuration.r')
```

Load plot specific libraries
```{r}
library(ggridges)
```

Read in and process data
```{r}
dat <- read.table('../tables/species_in_assembly_qc_pass.dat', head=TRUE, comment.char = '!') %>% 
  mutate(species=str_replace(X.species, '_',' '))
```

Select HAI species
```{r}
dat <-  filter(dat, grepl("Burkholderia", species) | 
               species %in% c("Acinetobacter baumannii","Candida albicans",
                         "Clostridium difficile", "Clostridium sordellii", 
                         "Klebsiella pneumoniae", "Klebsiella oxytoca",
                         "Escherichia coli", "Staphylococcus aureus",
                         "Pseudomonas aeruginosa","Mycobacterium abscessus",
                         "Mycobacterium tuberculosis","Enterococcus faecalis",
                         "Enterococcus faecium", "Staphylococcus epidermidis"))
```

Plot
```{r}
plot.dat <- group_by(dat, species) %>% 
  tally() %>% 
  merge(dat, by='species') %>%
  filter(n>19) 
  

g <- ggplot(data =plot.dat, aes(y=species,x=n50/1e6, fill=species)) +
  stat_density_ridges(quantile_lines = TRUE, quantiles = 2, alpha = 0.7) +
  scale_fill_manual(values=pal_simpsons(c("springfield"))(16)[-c(2,8)], guide=FALSE)+
  theme(axis.text.y = element_text(face='bold.italic'))  + 
  scale_x_log10() + 
  labs(y=NULL, x='N50 (MB)') +
  coord_cartesian(ylim =c(1,8))
g
```

Save plot
```{r, echo=FALSE}
ggsave('../plots/hai_ar_species_nanopore_n50.pdf', g,
       width=8, height=5)
```

