---
title: "Potential contaminant removal"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load generic libraries
```{r message=FALSE, warning=FALSE}
source('configuration.r')
```

Load specific libraries
```{r message=FALSE, warning=FALSE}
library(readr)
library(stringr)
library(gghighlight)
library(ggrepel)
library(magrittr)
library(ComplexHeatmap)
library(foreach)
```

### Species level analysis

```{r}
meta <- read.table('../metadata/illumina_metadata.txt', head=TRUE, row.names=2)
dat.s <- read.table('../tables/metagenomics.metaphlan2.table.s', head=TRUE, row.names=1)
dat.s[dat.s < 0.1] <- 0
dat.s <- dat.s[rowSums(dat.s)>0, ]
```

Detect taxa that are common in batch 1 and not detected in batch 2

```{r fig.height=8, fig.width=10}
batch1 <- dat.s[, filter(meta, timept %in% c(1, 2)) %>% pull(Library) ]
batch2 <- dat.s[, filter(meta, timept %in% c(3)) %>% pull(Library) ]

tmp <- cbind(
  (rowSums(batch1 > 0)/ncol(batch1)) %>% data.frame,
  (rowSums(batch2 > 0)/ncol(batch2)) %>% data.frame
) 
colnames(tmp) <- c('batch1', 'batch2')
tmp <- rownames_to_column(tmp, 'species') %>% 
  mutate(ratio=batch1/(batch2)) 
#head(tmp)

mutate(tmp, species=str_replace_all(species, c('s__'='', '_'=' '))) %>% 
  ggplot(aes(x=batch1, y=batch2, label=species)) + 
  geom_point(col='red', size=3)  + 
  gghighlight(ratio>4 & batch1>1/4) +
  geom_text_repel(col='black', fontface='italic',size=5) + 
  labs(x='Prevalence in timepoint 1 and 2', y='Prevalence in timepoint 3')
```

Check if the borderline species were correlated with the potential contaminants
```{r fig.height=11.5, fig.width=12}
species.removed <- filter(tmp,ratio>4 & batch1>1/4) %>% pull(species)

mat <- cor(t(batch1[tmp$batch1>0.25,]), method='spearman')

rownames(mat) %<>% str_replace_all(c('s__'='', '_'=' ')) %>% str_replace('[a-z]+ ', '. ')
colnames(mat) %<>% str_replace_all(c('s__'='', '_'=' ')) %>% str_replace('[a-z]+ ', '. ')
idx <-  which(rownames(batch1[tmp$batch1>0.25,]) %in% species.removed)

ha = rowAnnotation(foo = anno_mark(at =idx, rownames(mat)[idx], labels_gp = gpar(fontface='bold.italic')))
va = columnAnnotation(foo = anno_mark(at =idx, rownames(mat)[idx], side='bottom', 
                                      link_gp = gpar(col='red', lwd=2) ,
                                      labels_rot = 60,
                                      labels_gp = gpar(fontface='bold.italic', col='red', fontsize=20)))

Heatmap(mat, 
        #right_annotation = ha, 
        bottom_annotation = va,
        heatmap_legend_param = list(title='', legend_height=unit(5, "cm"), labels_gp=gpar(fontsize=15)), 
        #show_row_names = F, 
        show_column_names = F,
        row_names_gp=gpar(fontface = "bold.italic"), column_names_gp = gpar(fontface = "bold.italic")
        ) %>% 
  draw(heatmap_legend_side = "left")
```

<!-- Check correlation across batches -->
<!-- ```{r message=FALSE} -->
<!-- meta <- read.table('../metadata/illumina_metadata.txt', head=TRUE) -->
<!-- matching.ids <- select(meta, Library, Cubicle_room, Sample_type, Room_type, timept, bed_number) %>% -->
<!--   filter(timept %in% c(1,2,3)) %>%   -->
<!--   pivot_wider(names_from=timept, values_from=Library) %>%  -->
<!--   filter(!is.na(`1`), !is.na(`2`), !is.na(`3`)) -->

<!-- dat.hi_prev <- dat.s[tmp$batch1>0.5 & tmp$batch2>0.5, ] -->

<!-- d1 <- select(matching.ids, -`2`, -`3`) %>%  -->
<!--   merge(t(dat.hi_prev), by.x="1", by.y=0) %>%  -->
<!--   pivot_longer(cols = 6:ncol(.)) %>%  -->
<!--   select(everything(), tp1=value) %>%  -->
<!--   select(-`1`) -->

<!-- d2 <- select(matching.ids, -`1`, -`3`) %>%  -->
<!--   merge(t(dat.hi_prev), by.x="2", by.y=0) %>%  -->
<!--   pivot_longer(cols = 6:ncol(.)) %>%  -->
<!--   select(everything(), tp2=value) %>%  -->
<!--   select(-`2`) -->

<!-- d3 <- select(matching.ids, -`1`, -`2`) %>%  -->
<!--   merge(t(dat.hi_prev), by.x="3", by.y=0) %>%  -->
<!--   pivot_longer(cols = 6:ncol(.)) %>%  -->
<!--   select(everything(), tp3=value) %>%  -->
<!--   select(-`3`) -->

<!-- d.merged <-  -->
<!--   merge(d1, d2) %>%  -->
<!--   merge(d3) -->
<!--   #filter(!name %in% (species.removed)) %>%  -->
<!--   #mutate(name=str_replace(name, 's__', ''))  -->

<!-- ## calculate correlation -->
<!-- correlations <- -->
<!--   group_by(d.merged, Sample_type, name) %>%  -->
<!--   summarise(cor12=cor(tp1,tp2, method='spearman'), cor23=cor(tp2,tp3, method='spearman'), prev23=sum(tp2>0 & tp3>0)) -->

<!-- cor.contam <- filter(correlations, name %in% species.removed) %>%  -->
<!--   filter(!is.na(cor23)) -->

<!-- cor.control <-  -->
<!--   filter(correlations, !name %in% species.removed) %>% -->
<!--   filter(!is.na(cor23), cor23>0.5, prev23>5)  -->

<!-- ``` -->

<!-- ```{r fig.height=8, fig.width=16} -->
<!-- select(d.merged, -Cubicle_room, -Room_type, -bed_number) %>%  -->
<!--   merge(cor.contam) %>%  -->
<!--   ggplot( aes(x=tp2, y=tp3) ) +  -->
<!--   geom_point(size=3) +  -->
<!--   facet_wrap(Sample_type~name, scales = 'free', nrow=2) -->
<!-- ``` -->


<!-- ```{r fig.height=5, fig.width=16} -->
<!-- select(d.merged, -Cubicle_room, -Room_type, -bed_number) %>%  -->
<!--   merge(cor.control) %>%  -->
<!--   ggplot( aes(x=tp2, y=tp3) ) +  -->
<!--   geom_point(size=3) +  -->
<!--   scale_x_log10() +  -->
<!--   scale_y_log10() +  -->
<!--   facet_wrap(Sample_type~name, scales = 'free', nrow=1) -->
<!-- ``` -->


```{r}
write.table(species.removed, '../output_tables/contaminant_candidates.txt', quote=F, row.names = F, col.names = F)

dat.fil <- dat.s[!rownames(dat.s) %in% species.removed, ] 

## remaining proportion
boxplot(colSums(dat.fil))
```


Renormalize to 100%

```{r}
dat.fil <- apply(dat.fil, 2, function(x) x/sum(x)) * 100
write.table(dat.fil, '../output_tables/metagenomics.metaphlan2.table.filtered.s', sep='\t', row.names = TRUE, col.names = NA, quote=F)
```

### Genus level analysis

```{r}
dat.g <- read.table('../tables/metagenomics.metaphlan2.table.g', head=TRUE, row.names=1)
```

Remove genera detected above

```{r}
genera.affected <- dat.s[rownames(dat.s) %in% species.removed, ] %>% 
  mutate(g=row.names(.)) %>% 
  mutate(g=paste0('g__', ((species.removed) %>% str_split_fixed('_',4))[,3]) %>% str_replace("g__Propionibacterium", "g__Siphoviridae_noname")) %>% 
  group_by(g) %>% 
  summarise_all(sum) %>% 
  column_to_rownames('g')

dat.fil <- dat.g
dat.fil[rownames(dat.fil) %in% rownames(genera.affected), colnames(genera.affected)] <- dat.fil[rownames(dat.fil) %in% rownames(genera.affected), colnames(genera.affected)] - genera.affected

dat.fil[dat.fil < 0.1] <- 0
dat.fil <- dat.fil[rowSums(dat.fil)>0, ]
## remaining proportion
boxplot(colSums(dat.fil))
```

Renormalize to 100%

```{r}
dat.fil <- apply(dat.fil, 2, function(x) x/sum(x)) * 100
write.table(dat.fil, '../output_tables/metagenomics.metaphlan2.table.filtered.g', sep='\t', row.names = TRUE, col.names = NA, quote=F)
```