---
title: "Phylogenetic analysis based on identity and hive plot for species distribution"
output:
  html_document:
    df_print: paged
---

### Phylogenetic analysis based on identity

Load generic libraries
```{r}
source('configuration.r')
```

Load plot specific libraries
```{r}
library(ape)
library(ggtree)
library(HiveR)
```

Merge data
```{r}
df <- read.table('../tables/species_in_assembly_qc_pass.dat', head=TRUE, stringsAsFactors = FALSE, comment.char = '!')
meta.illumina <- read.table('../metadata/illumina_metadata.txt', head=TRUE)[,-2]
meta.nanopore <- read.table('../metadata/nanopore.metadata.txt', head=TRUE, sep='\t', strip.white = TRUE)
meta.merged <- merge(meta.nanopore, meta.illumina,
                     by.x='Illumina_Library_ID',
                     by.y='Library')
meta.merged <- merge(df, meta.merged,
                     by.x='lib',
                     by.y='Nanopore_ID')[,c(4,1:3,5:18)]
colnames(meta.merged)[3] <- 'Species'
write.table(meta.merged, '../metadata/merged_assembly_metadata.tsv', quote=F, row.names = F, col.names = T, sep='\t')
```


Function to plot the tree with heatmap
```{r}
## function to plot tree
plot.tree <- function(x, color, offset=0.01, title=NULL){
  dist.dat <- read.table(x)
  idx <- str_detect(rownames(dist.dat), 's_') & rownames(dist.dat) %in% meta.merged[,1]
  dist.dat <- dist.dat[idx, idx]
  
  ## clustering
  cluster.full <- hclust(as.dist(dist.dat), method='single')
  clusters <- cutree(cluster.full, h=0.001)
  
  strains <- sapply(unique(clusters), function(x) clusters[clusters==x][1])
  cluster.strains <- hclust(as.dist(dist.dat[names(strains), names(strains)]), method='single')
  
  merged <- merge(data.frame(clusters), meta.merged, by.x=0, by.y=1) %>%  
    mutate(strain=paste0('s', clusters))
  
  antibiotics <- select(merged, clusters, Antibiotics) %>% group_by(clusters, Antibiotics) %>% 
    count() %>% spread(Antibiotics,n,fill=0) %>% merge(data.frame(strains, id=names(strains)), by.x=1, by.y=1) %>% 
    select(-clusters, -BHI) %>% data.frame(row.names = 'id')
  antibiotics[antibiotics > 0] <- 'D'
  
  p <- ggtree(as.phylo(cluster.strains), layout="fan", open.angle=45, lwd=1.5) %<+%
    merged + 
    geom_tippoint(size=3, shape=19, col=color) +
    geom_tiplab2(aes(label=strain), size=5, offset=0.0015)
  
  p <- gheatmap(p, offset=offset, antibiotics, color='black', colnames_offset_y = 0.3,##colnames_offset_x=10,
                colnames_angle = 60, hjust =1, font.size=6.5) + scale_fill_manual(values=c('white', color)) + 
    theme(legend.position ='none') + 
    ggtitle(title)
  return(list(p=p, dat=merged))
}
```

Generate tree plots
```{r}
colors <- pal_d3('category20')(20)
g1 <- plot.tree('../tables/Acinetobacter_baumannii_mummer_heatmap.dat', colors[1], 0.007, 'Acinetobacter baumannii')
g2 <- plot.tree('../tables/Enterococcus_faecalis_mummer_heatmap.dat', colors[2], 0.004, 'Enterococcus faecalis')
g3 <- plot.tree('../tables/Staphylococcus_aureus_mummer_heatmap.dat', colors[3], 0.005, 'Staphylococcus aureus')
g4 <- plot.tree('../tables/Klebsiella_pneumoniae_mummer_heatmap.dat', colors[4], 0.005, 'Klebsiella pneumoniae')
g5 <- plot.tree('../tables/Pseudomonas_aeruginosa_mummer_heatmap.dat', colors[5], 0.004, 'Pseudomonas aeruginosa')
g6 <- plot.tree('../tables/Enterococcus_faecium_mummer_heatmap.dat', colors[6], 0.005, 'Enterococcus faecium')
g7 <- plot.tree('../tables/Staphylococcus_epidermidis_mummer_heatmap.dat', colors[7], 0.004, 'Staphylococcus epidermidis')
g8 <- plot.tree('../tables/Elizabethkingia_anophelis_mummer_heatmap.dat', colors[8], 0.004, 'Elizabethkingia anophelis')

write.table(rbind(g1$dat, g2$dat, g3$dat, g4$dat, g5$dat, g6$dat, g7$dat, g8$dat), 
            '../tables/strain_cluster_summary.tsv', sep='\t', row.names = F, col.names = T, quote=F)
```

Main figure part (*S. aureus*)

```{r fig.height=10, fig.width=10}
g3$p
```

Supplementary figure part
```{r fig.height=10, fig.width=60}
s1 <- cowplot::plot_grid(g1$p, g2$p, g4$p, g5$p, g6$p, g7$p, nrow=1)
s1
```


### Hive plot for species distribution

Generate edge data
```{r}
rbind(g1$dat, g2$dat, g3$dat, g4$dat, g5$dat, g6$dat, g7$dat) %>%
  group_by(Species, clusters, Sample_type, Room_type, #bed_number,
           timept, Sample_ID.y, Cubicle_room) %>%
  tally()  %>% ungroup() %>% 
  mutate(clusters=sprintf("%02d", clusters)) %>% 
  group_by(Species, clusters, Sample_type, Cubicle_room, Room_type, timept) %>% 
  count %>% select(-nn) %>% 
  mutate(label1='Strain', label2='Site', label3='Room') %>% 
  unite(n1,c(label1, Species, clusters), sep='=', remove=F) %>% 
  unite(n2,c(label2, Sample_type), sep='=', remove=F) %>% 
  unite(n3,c(label3, Room_type, Cubicle_room), sep='=',remove=F) %>% 
  select(-label1, -label2, -label3) -> edge_data

## remove strains only occurred once at one place
edge_data <- filter(edge_data, n1%in% 
         (edge_data %>% group_by(n1) %>% count %>% filter(n>1))$n1)
```

Hive plot function
```{r}
hiveplot <- function(species, col, silent=FALSE){ 
  edge_plot <- filter(edge_data ,Species==species)
  strain_col <- col
  
  rbind(data.frame(x1=edge_plot$n1, x2=edge_plot$n2, color=edge_plot$timept) ,
             data.frame(x1=edge_plot$n1, x2=edge_plot$n3, color=edge_plot$timept)
             ) %>% 
    group_by(x1, x2, color) %>% count() %>% 
    select(x1, x2, weight=n, color) %>% 
    arrange(desc(x1,x2)) -> e
  
  hive <- edge2HPD(data.frame(e[,1:3]))
  hive$nodes$axis <- as.integer(as.factor(str_split_fixed(hive$nodes$lab, '=', 2)[,1]))
  hive$nodes$tag <- str_split_fixed(hive$nodes$lab, '=', 3)[,1] 
  ## species color
  hive$nodes$color[ hive$nodes$tag == 'Strain'] <- strain_col
  ## site color
  colors <- sapply(c(pal_simpsons('springfield')(16)), adjustcolor, alpha.f=0.9)
  colormap <- data.frame(site=levels(edge_data$Sample_type), col=colors[1:9], row.names = 1, stringsAsFactors = F)
  site.id <- hive$nodes$tag=='Site'
  hive$nodes$color[site.id] <- colormap[str_split_fixed(hive$nodes$lab, '=', 2)[site.id, 2], ]
  ## room color
  colormap <-data.frame(room=unique(edge_data$Room_type), col=colors[c(13,15,16)], row.names = 1, stringsAsFactors = F)
  room.id <- hive$nodes$tag=='Room'
  hive$nodes$color[room.id] <- colormap[str_split_fixed(hive$nodes$lab[room.id], '=', 3)[,2], ]
  
  hive$nodes$size=2
  hive$edges$weight <- hive$edges$weight*3-1
  hive$edges$color <- ifelse(e$color<2, '#ff990055','#66ccff55')
  #hive$edges$color <- ifelse(e$color<2,'#66ccff77',  '#ff330077')
  tmp <- data.frame(node.lab=hive$nodes$lab, node.text=hive$nodes$lab, angle=0, radius=0, offset=0, hjust=1, vjust=0.5)
  mutate(tmp, node.text=str_replace(node.text, 'Strain=.*=', 'Strain=s')) %>% 
    separate(col=node.text, into=c('lab','node.text'), '=', extra='merge') %>% 
    mutate(node.text=str_replace_all(node.text, '_', ' ')) %>% 
    mutate(node.text=str_replace_all(node.text, '=', ': ')) %>% 
    mutate(offset=ifelse(lab=='Room' | lab=='Site' , -0.05, -0.03)) %>% 
    select(-lab) %>% 
  write.table('tmp_hive.txt', sep=',', quote=T, row.names = F, col.names = T)
  if(silent){return(hive)}
  plotHive(hive, ch=0.2, method='ranknorm', bkgnd='white', anNodes = 'tmp_hive.txt',
          anNode.gpar=gpar(cex=1.5))
}
```

Main figure part (*S. aureus*)
```{r fig.height=10, fig.width=10}
hiveplot('Staphylococcus_aureus', colors[3])
```



```{r fig.height=10, fig.width=60, message=FALSE}
aux <- function(){
  vplayout <- function(x, y) viewport(layout.pos.row = x, layout.pos.col = y)
  grid.newpage()
  pushViewport(viewport(layout = grid.layout(1, 6)))
  pushViewport(vplayout(1, 1)) # left plot
  h <- hiveplot('Acinetobacter_baumannii', colors[1], silent = TRUE)
  plotHive(h, ch=0.2, method='ranknorm', bkgnd='white', anNodes = 'tmp_hive.txt', np=FALSE,anNode.gpar=gpar(cex=1.5))
  popViewport(2)
  pushViewport(vplayout(1, 2))
  h <- hiveplot('Enterococcus_faecalis', colors[2], silent=TRUE)
  plotHive(h, ch=0.2, method='ranknorm', bkgnd='white', anNodes = 'tmp_hive.txt', np=FALSE,anNode.gpar=gpar(cex=1.5))
  
  popViewport(2)
  pushViewport(vplayout(1, 3))
  h <- hiveplot('Klebsiella_pneumoniae', colors[4], silent=TRUE)
  plotHive(h, ch=0.2, method='rank', bkgnd='white', anNodes = 'tmp_hive.txt', np=FALSE,anNode.gpar=gpar(cex=1.5))
  
  popViewport(2)
  pushViewport(vplayout(1, 4))
  h <- hiveplot('Pseudomonas_aeruginosa', colors[5], silent=TRUE)
  plotHive(h, ch=0.2, method='rank', bkgnd='white', anNodes = 'tmp_hive.txt', np=FALSE,anNode.gpar=gpar(cex=1.5))
  
  popViewport(2)
  pushViewport(vplayout(1, 5))
  h <- hiveplot('Enterococcus_faecium', colors[6], silent=TRUE)
  plotHive(h, ch=0.2, method='ranknorm', bkgnd='white', anNodes = 'tmp_hive.txt', np=FALSE,anNode.gpar=gpar(cex=1.5))
  
  popViewport(2)
  pushViewport(vplayout(1, 6))
  h <- hiveplot('Staphylococcus_epidermidis', colors[7], silent=TRUE)
  plotHive(h, ch=0.2, method='ranknorm', bkgnd='white', anNodes = 'tmp_hive.txt', np=FALSE,anNode.gpar=gpar(cex=1.5))
}
aux()
```


### Save plots
```{r}
ggsave('../plots/tree_main.pdf', g3$p, width=10, height=10)
pdf('../plots/hive_main.pdf', width = 10, height = 10)
hiveplot('Staphylococcus_aureus', colors[3])
dev.off()

ggsave('../plots/tree_sup.pdf', s1, width=48, height=8)
pdf('../plots/hive_sup.pdf', width = 48, height = 8)
aux()
dev.off()
```

### Session informaton
```{r}
sessionInfo()
```

