---
title: "Plasmid Rarefaction"
output:
  html_document:
    df_print: paged
---


### generate plasmid rarefaction plots

Load generic libraries
```{r message=FALSE, warning=FALSE}
source('configuration.r')
```

Load specific libraries
```{r message=FALSE, warning=FALSE}
library(matrixStats)
library(iNEXT)
```

plasmid with antibiotic resistant genes
```{r message=FALSE, warning=FALSE}
cluster <-read.table("../output_tables/plasmid_cluster.tsv",
                     row.names = NULL, sep="\t")
names(cluster) <- c("Plasmid_ID", "cluster")
cluster <- cluster[grepl("p_",cluster$Plasmid_ID), ]

plasmid_info <- read.csv("../tables/plasmid_info.dat", sep="\t", header=TRUE)
nanopore_meta <- read.table("../metadata/nanopore.metadata.txt", header=TRUE)

meta_assembly_merge_filter <-  merge(nanopore_meta, plasmid_info, by = "Nanopore_ID", all = TRUE, sort = FALSE)
meta_assembly_merge_filter <-  merge(meta_assembly_merge_filter, cluster, by = "Plasmid_ID", all = TRUE, sort = FALSE)

# sort dataframe
meta_assembly_merge_filter <-  meta_assembly_merge_filter[order(meta_assembly_merge_filter$Sample_ID, 
                                                                meta_assembly_merge_filter$Nanopore_ID),, drop=TRUE]
row.names(meta_assembly_merge_filter) <- NULL

keep <- c("Plasmid_ID", "Sample_ID","Nanopore_ID", "cluster", "Number_of_AR_genes", "AR_gene_list")
meta_assembly_merge_filter <- meta_assembly_merge_filter[keep]
# drop na Sample_ID
meta_assembly_merge_filter <-  meta_assembly_merge_filter[!is.na(meta_assembly_merge_filter$Sample_ID),]

meta_assembly_merge_filter$patho <- ifelse(meta_assembly_merge_filter$Number_of_AR_genes != 0 , meta_assembly_merge_filter$cluster, NA)
meta_assembly_merge_filter$patho_1 <- ifelse(meta_assembly_merge_filter$Number_of_AR_genes > 1 , meta_assembly_merge_filter$cluster, NA)
```

rarefaction figure
```{r fig.height=48, fig.width=8, message=FALSE, warning=FALSE}

all_sampling_matrix <- acast(meta_assembly_merge_filter, cluster~Sample_ID, value.var="cluster")
all_sampling_matrix <- all_sampling_matrix[rownames(all_sampling_matrix) !="NA", ]
all_sampling_matrix <- all_sampling_matrix[,colnames(all_sampling_matrix) !="NA"]
all_sampling_matrix <- all_sampling_matrix[,] > 0

patho_sampling_matrix <- acast(meta_assembly_merge_filter, patho~Sample_ID, value.var="patho")
patho_sampling_matrix <- patho_sampling_matrix[rownames(patho_sampling_matrix) !="NA", ]
patho_sampling_matrix <- patho_sampling_matrix[,colnames(patho_sampling_matrix) !="NA"]
patho_sampling_matrix <- patho_sampling_matrix[,] > 0

patho_1_sampling_matrix <- acast(meta_assembly_merge_filter, patho_1~Sample_ID, value.var="patho_1")
patho_1_sampling_matrix <- patho_1_sampling_matrix[rownames(patho_1_sampling_matrix) !="NA", ]
patho_1_sampling_matrix <- patho_1_sampling_matrix[,colnames(patho_1_sampling_matrix) !="NA"]
patho_1_sampling_matrix <- patho_1_sampling_matrix[,] > 0


all_out <- iNEXT(all_sampling_matrix, datatype="incidence_raw", endpoint = 8000)
g1 <- ggiNEXT(all_out, color.var="order") +
    geom_line(aes(y=all_out$AsyEst["Species Richness", "Estimator"]), size = 0.5, linetype = "dashed", color = "black") +
    scale_y_continuous(breaks = c(seq(0 , 10000, by=2000), round(all_out$AsyEst["Species Richness", "Estimator"]))) +
    labs(title = "Rarefaction of circular plasmids", x = "number of samples")
g1 <- g1 + guides(fill=FALSE)
g1 <- g1 + scale_color_discrete(labels = c("richness")) + 
  scale_shape_discrete(labels = c("richness"))

index_out <- iNEXT(all_sampling_matrix, q=c(1,2), datatype="incidence_raw", endpoint = 5000)
g2 <- ggiNEXT(index_out, color.var="order") +
    geom_line(aes(y=index_out$AsyEst["Shannon diversity", "Estimator"]), size = 0.5, linetype = "dashed", color = "black") + 
    geom_line(aes(y=index_out$AsyEst["Simpson diversity", "Estimator"]), size = 0.5, linetype = "dashed", color = "black") +
    scale_y_continuous(breaks = c(seq(0 , 3000, by=500), round(index_out$AsyEst["Shannon diversity", "Estimator"]), round(index_out$AsyEst["Simpson diversity", "Estimator"])))+
    labs(title = "Rarefaction of circular plasmids", y = "diversity index", x = "number of samples")
g2 <- g2 + guides(fill=FALSE)
g2 <- g2 + scale_color_discrete(labels = c("shannon", "simpson")) + 
  scale_shape_discrete(labels = c("shannon", "simpson"))

patho_out <- iNEXT(patho_sampling_matrix, datatype="incidence_raw", endpoint = 8000)
g3 <- ggiNEXT(patho_out, color.var="order") +
    geom_line(aes(y=patho_out$AsyEst["Species Richness", "Estimator"]), size = 0.5, linetype = "dashed", color = "black") +
    scale_y_continuous(breaks = c(seq(0 , 3000, by=500), round(patho_out$AsyEst["Species Richness", "Estimator"]))) +
    labs(title = "Rarefaction of circular plasmids > 0 AR gene", x = "number of samples")
g3 <- g3 + guides(fill=FALSE)
g3 <- g3 + scale_color_discrete(labels = c("richness")) + 
  scale_shape_discrete(labels = c("richness"))

patho_index <- iNEXT(patho_sampling_matrix, q = c(1,2), datatype="incidence_raw", endpoint = 5000)
g4 <- ggiNEXT(patho_index, color.var="order") +
    geom_line(aes(y=patho_index$AsyEst["Shannon diversity", "Estimator"]), size = 0.5, linetype = "dashed", color = "black") + 
    geom_line(aes(y=patho_index$AsyEst["Simpson diversity", "Estimator"]), size = 0.5, linetype = "dashed", color = "black") +
    scale_y_continuous(breaks = c(seq(0 , 1000, by=100), round(patho_index$AsyEst["Shannon diversity", "Estimator"]), round(patho_index$AsyEst["Simpson diversity", "Estimator"])))+
    labs(title = "Rarefaction of circular plasmids > 0 AR gene", y = "diversity index", x = "number of samples")
g4 <- g4 + guides(fill=FALSE)
g4 <- g4 + scale_color_discrete(labels = c("shannon", "simpson")) + 
  scale_shape_discrete(labels = c("shannon", "simpson"))

patho_1_out <- iNEXT(patho_1_sampling_matrix, datatype="incidence_raw", endpoint = 8000)
g5 <- ggiNEXT(patho_1_out, color.var="order") +
    geom_line(aes(y=patho_1_out$AsyEst["Species Richness", "Estimator"]), size = 0.5, linetype = "dashed", color = "black") +
    labs(title = "Rarefaction of circular plasmids > 1 AR gene", x = "number of samples")
g5 <- g5 + guides(fill=FALSE)
g5 <- g5 + scale_color_discrete(labels = c("richness")) + 
  scale_shape_discrete(labels = c("richness"))

patho_1_index <- iNEXT(patho_1_sampling_matrix, q=c(1,2), datatype="incidence_raw", endpoint = 5000)
g6 <- ggiNEXT(patho_1_index, color.var="order") +
    geom_line(aes(y=patho_1_index$AsyEst["Shannon diversity", "Estimator"]), size = 0.5, linetype = "dashed", color = "black") + 
    geom_line(aes(y=patho_1_index$AsyEst["Simpson diversity", "Estimator"]), size = 0.5, linetype = "dashed", color = "black") +
    scale_y_continuous(breaks = c(seq(0 , 1000, by=60), round(patho_1_index$AsyEst["Shannon diversity", "Estimator"])))+
    labs(title = "Rarefaction of circular plasmids > 1 AR gene", y = "diversity index", x = "number of samples")
g6 <- g6 + guides(fill=FALSE)
g6 <- g6 + scale_color_discrete(labels = c("shannon", "simpson")) + 
  scale_shape_discrete(labels = c("shannon", "simpson"))

cowplot::plot_grid(g1, g2, g3, g4, g5, g6, nrow=6)

ggsave('../plots/circular_plasmid_rarefaction.pdf', height = 48, width = 8)

```

### Session informaton
```{r}
sessionInfo()
```