---
title: "PCoA plots comparing samples across Singapore"
output:
  html_document:
    df_print: paged
---

## PCoA plots for hospital, office, and MetaSUB data

Load generic libraries
```{r message=FALSE, warning=FALSE}
source('configuration.r')
```

Load specific libraries
```{r message=FALSE, warning=FALSE}
library(readr)
library(vegan)
library(ggpubr)
```

Process and merge metadata
```{r message=FALSE, warning=FALSE}
meta <- read_csv("../tables/metasub_singapore/complete_metadata.csv")
dat <- read_tsv("../tables/metasub_singapore/g.metaphlan2.profile_merged.tsv") %>% 
  column_to_rownames("Index")

meta_hosp <- read_tsv("../metadata//illumina_metadata.txt")
dat_hosp <- read_tsv("../tables/metagenomics.metaphlan2.table.g") %>% 
  column_to_rownames("Index")

# remove samples with missing metadata
missing_dat <- filter(meta, is.na(meta$metasub_name))$uuid

# filter for high human contact sites
meta_fil <-
  meta %>% 
  filter(!(uuid %in% missing_dat)) %>% 
  mutate(uuid = str_remove(uuid, "hai.*XY_")) %>% 
  mutate(site = "MetaSUB") %>% 
  filter(surface %in% c("handrail",
                        "lift_buttons",
                        "overhead_handrail",
                        "pedestrian_crossing_button",
                        "playground",
                        "seat",
                        "table",
                        "exercise_hand_grip")) 

select( library_id = uuid, meta_fil, metasub_name, city, surface_material, site=surface, setting) %>% 
  write.table('../output_tables/metasub_99samples_metadata.tsv', quote=F, row.names = F, sep='\t')

meta_fil <- 
  select(meta_fil, uuid, site) 

# remove mock and control samples, filter for time point 1 only
meta_hosp_fil <-
  meta_hosp %>%
  select(Library, Room_type, Sample_type, timept) %>% 
  filter(Room_type != "Mock") %>% 
  filter(!str_detect(Room_type, "Control")) %>% 
  filter(is.na(timept) | timept == 1) %>% 
  rename("uuid" = "Library") %>% 
  mutate(site = if_else(Room_type == "GIS", "Office", "Hospital")) %>% 
  mutate(site_ct = if_else(Sample_type %in% c('Sink_Trap', 'Aerator'), 'CTB', 'CTA')) %>%
  select(uuid, site, site_ct)

meta_merged <-
  merge(meta_fil, meta_hosp_fil, all = TRUE) %>% 
  mutate(site_ct = if_else(is.na(site_ct), 'MetaSUB', site_ct)) %>% 
  column_to_rownames("uuid")
```

Process data and generate figure (Using time point 1 only)
```{r fig.height=6, fig.width=8, message=FALSE, warning=FALSE}
dat_merged <-
  merge(dat, dat_hosp, by = "row.names", all = TRUE) %>%
  column_to_rownames("Row.names") %>% 
  replace(is.na(.), 0)

dat_merged_fil <- dat_merged[, as.character(rownames(meta_merged))]
dat_merged_fil[dat_merged_fil < 0.1] <- 0
dat_merged_fil <- dat_merged_fil[rowSums(dat_merged_fil) > 0, ]

dist_mat <- vegdist(t(dat_merged_fil))
cmds <- cmdscale(dist_mat, k = 3, eig = TRUE)
eigen <- cmds$eig / sum(cmds$eig) * 100

dat_merged_all <- (merge(cmds$points, meta_merged, by.x=0, by.y=0, all = TRUE)) %>%
  unite(col="lab", site, site_ct)


ggplot(dat_merged_all, aes(x = V1, y = V2, fill = lab, label = Row.names), lwd=2) +
  geom_density_2d(aes(x = V1, y = V2), inherit.aes = FALSE, col = 'grey', lwd=1) + 
  geom_point(data=subset(dat_merged_all, lab=='MetaSUB_MetaSUB'), size = 3, shape=21, alpha=0.6) +
  geom_point(data=subset(dat_merged_all, str_detect(lab, 'Hospital')), size = 3, shape=21, alpha=0.6) +
  geom_point(data=subset(dat_merged_all, str_detect(lab, 'Office')), size = 3, shape=21, alpha=0.6) +
  labs(x=paste0('PCoA1 (',round(eigen[1], 1),'%)'),
       y=paste0('PCoA2 (',round(eigen[2], 1),'%)')) +
  scale_fill_manual(values=c('darkgreen', 'green', 'blue', 'red', 'pink')) + 
  theme(legend.title = element_blank(), legend.background = element_blank(),
        legend.key = element_blank(), legend.text = element_text(size = 12))

ggsave('../plots/sup2.pcoa_across_singapore.png', height = 6, width = 8)

```


CTX hospital vs. office
```{r fig.height=6, fig.width=8}
dist.mat <- as.matrix(dist_mat)
diag(dist.mat) <- NA
dist.cta <- dist.mat[
  rownames_to_column(meta_merged) %>% 
    filter( site_ct=='CTA', site=='Office') %>% pull(1),
  rownames_to_column(meta_merged) %>% 
    filter( site_ct=='CTA', site=='Hospital') %>% pull(1)
] %>% c %>% data.frame(bray=., type='CTA vs. CTA-like')
dist.cta.office <- dist.mat[
  rownames_to_column(meta_merged) %>% 
    filter( site_ct=='CTA', site=='Office') %>% pull(1),
  rownames_to_column(meta_merged) %>% 
    filter( site_ct=='CTA', site=='Office') %>% pull(1)
] %>% c %>% data.frame(bray=., type='CTA-like vs. CTA-like') %>% 
  filter(!is.na(bray))
g1 <- 
  rbind(dist.cta, dist.cta.office) %>% 
    ggplot(aes(x=type, y=bray, fill=type)) + 
    geom_boxplot(lwd=1.5) +
    scale_y_continuous(limits=c(0,1.2), breaks=c(0,0.5,1)) + 
    labs(x=NULL, y='Bray-Curtis distance') +
    scale_fill_aaas(guide=F) + 
    theme(axis.text.x = element_text(angle=40, hjust=1)) + 
    stat_compare_means(comparisons = list(c("CTA vs. CTA-like", "CTA-like vs. CTA-like")), label = "p.signif", size=15)
dist.ctb <- dist.mat[
  rownames_to_column(meta_merged) %>% 
    filter( site_ct=='CTB', site=='Office') %>% pull(1),
  rownames_to_column(meta_merged) %>% 
    filter( site_ct=='CTB', site=='Hospital') %>% pull(1)
] %>% c %>% data.frame(bray=., type='CTB vs. CTB-like')
dist.ctb.office <- dist.mat[
  rownames_to_column(meta_merged) %>% 
    filter( site_ct=='CTB', site=='Office') %>% pull(1),
  rownames_to_column(meta_merged) %>% 
    filter( site_ct=='CTB', site=='Office') %>% pull(1)
] %>% c %>% data.frame(bray=., type='CTB-like vs. CTB-like')%>% 
  filter(!is.na(bray))
g2 <- 
  rbind(dist.ctb, dist.ctb.office) %>% 
    ggplot(aes(x=type, y=bray, fill=type)) + 
    geom_boxplot(lwd=1.5) +
    scale_y_continuous(limits=c(0,1.2), breaks=c(0,0.5,1)) + 
    labs(x=NULL, y='Bray-Curtis distance') +
    scale_fill_aaas(guide=F) + 
    theme(axis.text.x = element_text(angle=40, hjust=1)) + 
    stat_compare_means(comparisons = list(c("CTB vs. CTB-like", "CTB-like vs. CTB-like")), label = "p.signif", size=15)
cowplot::plot_grid(g1, g2)
ggsave('../plots/sup2.CT_across_singapore.png', height = 6, width = 8)
```

Generate figure for all time points
```{r fig.height=5.5, fig.width=9, message=FALSE, warning=FALSE}
meta_hosp_fil_all <-
  meta_hosp %>%
  select(Library, Room_type, Sample_type, timept) %>% 
  filter(Room_type != "Mock") %>% 
  filter(!str_detect(Room_type, "Control")) %>% 
  rename("uuid" = "Library") %>% 
  mutate(site = if_else(Room_type == "GIS", "Office",
                        if_else(Sample_type == "Aerator" | Sample_type == "Sink_Trap", "CTB", "CTA"))) %>%
  select(uuid, site, timept)

meta_merged_all <- 
  merge(meta_fil, meta_hosp_fil_all, all = TRUE) %>% 
  column_to_rownames("uuid")

dat_merged_fil <- dat_merged[, as.character(rownames(meta_merged_all))]
dat_merged_fil[dat_merged_fil < 0.1] <- 0
dat_merged_fil <- dat_merged_fil[rowSums(dat_merged_fil) > 0, ]

dist_mat_all <- vegdist(t(dat_merged_fil))

# ## scratch
# cmds <- cmdscale(dist_mat_all, k = 3, eig = TRUE)
# eigen <- cmds$eig / sum(cmds$eig) * 100
# 
# dat_merged_all <- (merge(cmds$points, meta_merged_all, by.x=0, by.y=0, all = TRUE))
# 
# ggplot(dat_merged_all, aes(x=V1, y=V2, fill=site, label=Row.names)) +
#   geom_point(shape=21)
```

Get matched samples
```{r message=FALSE, warning=FALSE}
dists <- as.matrix(dist_mat_all) %>% 
  melt() %>% 
  filter(!str_detect(Var1, "SL") & !str_detect(Var2, "SL")) %>% 
  filter(str_detect(Var1, "MEM") | Var1 %in% c("WEE330", "WEE349", "WEE368", "WEE387", "WEE388")) %>% 
  filter(!str_detect(Var2, "MEM") & !Var2 %in% c("WEE330", "WEE349", "WEE368", "WEE387", "WEE388")) %>% 
  arrange(value)

dists_matched <- setNames(data.frame(matrix(ncol = 3, nrow = 0)), c("Var1", "Var2", "value"))

n <- 1
while (n <= 12) {
  if (!(dists[1,]$Var1 %in% dists_matched$Var1) & !(dists[1,]$Var2 %in% dists_matched$Var2)) {
    dists_matched[n,]$Var1 <- as.character(dists[1,]$Var1)
    dists_matched[n,]$Var2 <- as.character(dists[1,]$Var2)
    dists_matched[n,]$value <- as.character(dists[1,]$value)
    n <- n + 1
  }
  dists <- dists[-1,]
}

write.table(dists_matched, "../output_tables/matched_pairs.txt", quote = F, row.names = F, col.names = F)

matched_samples <-
  dists_matched %>% 
  select(-value) %>% 
  gather() %>% 
  select(value)

write.table(matched_samples, "../output_tables/matched_samples.txt", quote = F, row.names = F, col.names = F)

```

Session information

```{r}
sessionInfo()
```