---
title: "Supplimentary Figure 2"
output:
  html_document:
    df_print: paged
---

### Supplementary Figure 2

Load generic libraries
```{r}
source('configuration.r')
```

Load plot specific libraries
```{r message=FALSE}
library(vegan)
library(reshape2)
```

#### Suppl Fig 1

```{r fig.height=8, fig.width=10}
meta <- read.table('../metadata/illumina_metadata.txt', head=TRUE, row.names=2)

dat <- read.table('../tables/metagenomics.metaphlan2.table.g', head=TRUE, row.names=1)
dat[dat < 0.1] <- 0
dat <- dat[rowSums(dat)>0, ]
meta.filled <- meta %>% select(Library,Room_type, Sample_type, Cubicle_room, timept)
dat.fil=filter(meta.filled,Room_type != 'GIS' & Room_type != 'Negative controls' & timept == 1)
dat.fil = mutate(dat.fil, MDRO=ifelse(Room_type == "MDRO_cubicles", "MDRO_","")) %>% unite(MDRO,Cubicle_room,col="Cubicle_room",sep="")
dat.fil.dat=select(dat,matrix(unlist(dat.fil["Library"]))[,1])
Shan=data.frame(Shannon=(diversity(t(dat.fil.dat),index="shannon"))) %>% 
  rownames_to_column('Library')
Simp=data.frame(Simpson=diversity(t(dat.fil.dat),index="simpson"))%>% 
  rownames_to_column('Library')
diversity=group_by(dat.fil,Sample_type,Library) %>% summarise() %>% merge(Shan, by ="Library") %>% merge(Simp, by="Library")

melt(diversity) %>% 
  mutate(Sample_type=str_replace(Sample_type, '_', ' ')) %>%
  mutate(Sample_type=str_replace(Sample_type, '-interior', '')) %>%
  mutate(Sample_type=relevel(factor(.$Sample_type), 'Sink Trap')) %>% 
  ggplot(aes(x=Sample_type,y=value,fill=Sample_type)) +
  geom_violin() +
  theme(axis.text.x = element_text(angle=40, vjust=1, hjust=1)) + 
  scale_fill_manual(values=pal_npg(c("nrc"))(10)[c(1,5,7,2,3,10,4)]) + 
  facet_wrap(~variable, nrow=2, scale='free_y')
ggsave('../plots/sup2.metagenomics_diversity.pdf', height = 8, width=10)
```



